variables:
  resource-group: 'AZ400-EWebShop-Rehan'
  location: 'centralus'
  templateFile: 'infra/simple-windows-vm.bicep'
  azureserviceconnection: 'DevOps(e4cc4d5c-bd21-4ee9-b0a8-a990e1f71674)'

stages:
- stage: Deploy
  displayName: Deploy the Bicep template
  jobs:
  - job: Deploy
    pool:
      name: "Default"
    steps:
    - checkout: self
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureserviceconnection)
        scriptType: ps
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group create -l $(location) -n $(resource-group)
          
          az deployment group create -f $(templateFile) -g $(resource-group)
