#NAME THE PIPELINE SAME AS FILE (WITHOUT ".yml")

# trigger: none
resources:
  pipelines:
  - pipeline: eshoponweb-ci-dockercompose
    source: eshoponweb-ci-dockercompose # given pipeline name
    trigger: true
  repositories:
    - repository: self
      trigger: none

variables:
  location: 'centralus'
  templateFile: 'infra/aci.bicep'
  subscriptionid: 'e4cc4d5c-bd21-4ee9-b0a8-a990e1f71674'
  azureserviceconnection: 'DevOps(e4cc4d5c-bd21-4ee9-b0a8-a990e1f71674)'
  webappname: 'az400eshop-rg-aci-webapp'
  acr-login-server: 'crktkitftp3wgks.azurecr.io'
  acr-username: 'crktkitftp3wgks'
  resource-group: 'rg-eshop'


stages:
- stage: Deploy
  displayName: Docker Compose to ACI
  #variable group referencing KV secret
  variables:
  - group: 'eshopweb-vg'
  jobs:
  - job: Deploy
    pool:
      name: 'Default'
    steps:
    # Deploy Azure Container Instance using Bicep
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy ACI Bicep
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(azureserviceconnection)'
        subscriptionId: '$(subscriptionid)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resource-group)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(templateFile)'
        overrideParameters: ' -name $(webappname) -image $(acr-login-server)/eshopwebmvc:latest -server $(acr-login-server) -username $(acr-username) -password $(acr-secret)'
        deploymentMode: 'Incremental'
        # deploymentOutputs: 'asp-json'
    